"""cascade id dosen di table mhs

Revision ID: 43243eb56f99
Revises: 6c0df42c6e7c
Create Date: 2024-01-15 11:10:28.035517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43243eb56f99'
down_revision = '6c0df42c6e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint('mahasiswa_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('mahasiswa_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dosen', ['dosen_satu'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dosen', ['dosen_dua'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('mahasiswa_ibfk_2', 'dosen', ['dosen_satu'], ['id'])
        batch_op.create_foreign_key('mahasiswa_ibfk_1', 'dosen', ['dosen_dua'], ['id'])

    # ### end Alembic commands ###
