"""tambah gambar di tabel Dosen

Revision ID: a28a9937b84a
Revises: 585ede6e47c8
Create Date: 2024-01-16 08:06:01.988292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a28a9937b84a'
down_revision = '585ede6e47c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gambar', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dosen', schema=None) as batch_op:
        batch_op.drop_column('gambar')

    # ### end Alembic commands ###
